<a href="https://colab.research.google.com/github/varshabantu/Data-Science-Tasks/blob/main/Numpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l=[10,12,34,5.6,7.8]

type(l)

list

list

In [ ]:
[1,2,3]+[4,5,6]
[1,2,3]-[4,5,6]
[1,2,3]*[4,5,6]
[1,2,3]/[4,5,6]
[1,2,3]//[4,5,6]
[1,2,3]%[4,5,6]

[1, 2, 3, 4, 5, 6]

In [ ]:
import numpy as np


In [ ]:
#1. Array Creation
import numpy as np
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([10,20,3.4,40,50])
print(arr1,arr2)

[10 20 30 40 50] [10.  20.   3.4 40.  50. ]


In [ ]:
#datatype convertion priority
# bool
# int
# float
# complex
# str
# object datatype (numpy always call set,dict as object datatype)

import numpy as np
arr1=np.array([12,3.6,67,8]) #int, float
arr2=np.array([12,3.6,5+6j,8]) #complex
arr3=np.array([12,3.6,5+6j,"Hiii",67,8])  #string
arr4=np.array([12,3.6,5+6j,"Hiii",{1,2,3},67,8]) #Set # Here set is consider as object datatype.
# We never use data using 'set'
print(arr1,arr2,arr3,arr4)




[12.   3.6 67.   8. ] [12. +0.j  3.6+0.j  5. +6.j  8. +0.j] ['12' '3.6' '(5+6j)' 'Hiii' '67' '8'] [12 3.6 (5+6j) 'Hiii' {1, 2, 3} 67 8]


In [ ]:
#2. Types of Arrays
# 1.One-dimensional array / Uni-dimenstional array
# 2.Bi-dimensional array (2D)
# 3.Multi-dimensional array(N D)

import numpy as np

#1. Uni-dimensional (1D)
arr = np.array([3,4,5,6.7,89])
print(arr)

#2. Bi-dimensional (2D)
arr = np.array([[1,2,3],
                [4,5,6],
                 [7,8,9]])
print(arr)
#3. Multi-dimensional array (N-D)

arr=np.array([[[1,2,3,4],             #Yellow color brackets are called columns
               [4,5,6,7]],

              [[3,4,5,9],
               [6,7,9,10]]])

print(arr)

[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 3  4  5  9]
  [ 6  7  9 10]]]


In [ ]:
#3. Key Functions of Numpy
#1. np.__version__: It is the inbuit attribute which is used to check the version of library
np.__version__

#2. np.array(): It is an inbuild method which is used to create an arrays.
np.array((1,2,3,4,5,6,7,8,9,10))

#3. arr.ndim: It is an inbuild attribute which is used to find the type of dimension.
arr.ndim
arr1.ndim
arr2.ndim

#4. arr.dtype: It is an inbuild attribute, whivh is used to find the datatype of an array.
arr.dtype
arr1.dtype
arr2.dtype

#5. np.arange(sv,ev+1,upd/step): It is an inbuild method, it is used to create a uni-dimension array within specified limits.

#Simulated data of temperature values in hyderabad.
import numpy as np
hyd_temp = np.arange(-10,51)
print(hyd_temp)

a = np.arange(1,200001)
b = np.arange(1,10000000,3)
c = np.arange(10000000,0,-1) # In reverse direction and decrease the values
print(a,b,c)

[10000000  9999999  9999998 ...        3        2        1]


In [ ]:
#6. arr.shape: It is an inbuild attribute, it will return the no.of rows and columns.
arr.shape
# arr1.shape
# arr2.shape

#7. arr.reshape(r,c): It is an inbuild method, it is help us to convert from one dimension to another dimension.
import numpy as np
arr=np.array([3,4,5,6.7,89,90,78])
# arr.reshape(2,3)
# arr.reshape(3,2)
arr.reshape(1,7)
arr.reshape(7,1)
print(arr)
# Rule: The product of rows and columns should be equal to total values

# Flatenning the array: n D ---> 1D
# Syntax: arr.reshape(-1)

arr1.reshape(-1)
arr2.reshape(-1)
arr3.reshape(-1)

[ 3.   4.   5.   6.7 89.  90.  78. ]


array(['12', '3.6', '(5+6j)', 'Hiii', '67', '8'], dtype='<U64')

In [ ]:
#8. np.linspace(sv,ev,n): It will return an array which is one dimensional array, with equally spaced values.

np.linspace(1,5,10)
np.linspace(1,6,1000)
price = np.linspace(1,10000)
print(price)
price


[1.00000000e+00 2.05061224e+02 4.09122449e+02 6.13183673e+02
 8.17244898e+02 1.02130612e+03 1.22536735e+03 1.42942857e+03
 1.63348980e+03 1.83755102e+03 2.04161224e+03 2.24567347e+03
 2.44973469e+03 2.65379592e+03 2.85785714e+03 3.06191837e+03
 3.26597959e+03 3.47004082e+03 3.67410204e+03 3.87816327e+03
 4.08222449e+03 4.28628571e+03 4.49034694e+03 4.69440816e+03
 4.89846939e+03 5.10253061e+03 5.30659184e+03 5.51065306e+03
 5.71471429e+03 5.91877551e+03 6.12283673e+03 6.32689796e+03
 6.53095918e+03 6.73502041e+03 6.93908163e+03 7.14314286e+03
 7.34720408e+03 7.55126531e+03 7.75532653e+03 7.95938776e+03
 8.16344898e+03 8.36751020e+03 8.57157143e+03 8.77563265e+03
 8.97969388e+03 9.18375510e+03 9.38781633e+03 9.59187755e+03
 9.79593878e+03 1.00000000e+04]


array([1.00000000e+00, 2.05061224e+02, 4.09122449e+02, 6.13183673e+02,
       8.17244898e+02, 1.02130612e+03, 1.22536735e+03, 1.42942857e+03,
       1.63348980e+03, 1.83755102e+03, 2.04161224e+03, 2.24567347e+03,
       2.44973469e+03, 2.65379592e+03, 2.85785714e+03, 3.06191837e+03,
       3.26597959e+03, 3.47004082e+03, 3.67410204e+03, 3.87816327e+03,
       4.08222449e+03, 4.28628571e+03, 4.49034694e+03, 4.69440816e+03,
       4.89846939e+03, 5.10253061e+03, 5.30659184e+03, 5.51065306e+03,
       5.71471429e+03, 5.91877551e+03, 6.12283673e+03, 6.32689796e+03,
       6.53095918e+03, 6.73502041e+03, 6.93908163e+03, 7.14314286e+03,
       7.34720408e+03, 7.55126531e+03, 7.75532653e+03, 7.95938776e+03,
       8.16344898e+03, 8.36751020e+03, 8.57157143e+03, 8.77563265e+03,
       8.97969388e+03, 9.18375510e+03, 9.38781633e+03, 9.59187755e+03,
       9.79593878e+03, 1.00000000e+04])

In [ ]:
#9. np.zeros(): it creates an array filled with only zeros.

# Syntax: 1. np.zeros(n) ---->1D
         #2. np.zeros((r,c)) --->2D
         #3. np.zeros((r,c,n)) --->3D
np.zeros(5)
np.zeros((3,4))
np.zeros((3,2,4))


#10. np.ones(): It creates an array filled with only ones.

# Syntax: 1. np.ones(n) --->1D
         #2. np.ones((r,c)) --->2D
         #3. np.ones((r,c,n)) --->3D

np.ones(10)
np.ones((3,4))
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
#11. np.identity(n): It creates an identity matrix.

np.identity(3)
np.identity(5)
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
#12. np.random.randint(sv,ev+-1,n): It is used to generates the integer data  randomly value.

import random
random.randint(1,100)

np.random.randint(1,100,10)
age = np.random.randint(1,100,1000)
temp = np.random.randint(-10,38,500)
sales = np.random.randint(1,10000,100000)
print(sales)
# print(age)
# print(temp)

[5887 6662 2401 ... 6124 1529  297]


In [ ]:
#13. np.random.rand(n): It always generate values in between 0 to 1.

measurement = np.random.rand(1000)
# print(measurement)


#14. np.random.randn(n): It creates data between -infinte to +infinte

np.random.randn(500)


array([-6.59279114e-01,  1.14020797e+00,  1.25760999e-01,  6.23906905e-01,
        2.50733910e-01, -6.47002255e-01, -2.38371172e+00,  1.87929659e+00,
        4.36298659e-01,  1.57673751e+00,  6.03674514e-01,  1.53178221e-02,
        2.66140465e-01, -7.64185252e-01, -1.01697893e-01,  1.45866993e+00,
        1.69283111e+00, -1.97477190e+00,  1.14233860e+00, -2.49893004e-01,
        1.21823118e+00,  4.50276681e-01,  1.53163015e+00,  1.06200515e+00,
        1.73019100e+00,  1.39551360e+00, -2.19424094e-01,  9.13438991e-01,
        1.23119810e+00,  1.22822137e-01, -5.20275901e-02,  3.90715043e-02,
       -2.91175925e-01, -4.84609456e-01,  8.21241801e-01,  6.14020538e-01,
       -5.29319122e-01,  3.61034534e-01, -3.48733519e-01, -1.44238832e-01,
       -8.42178971e-01,  5.20914778e-01,  5.40174766e-01,  1.49633343e+00,
       -2.09210050e+00, -2.80441279e-01, -7.71548616e-01,  1.37736228e+00,
        4.08265266e-01, -3.12969571e-01,  1.42748951e+00,  9.82662274e-01,
        4.11046073e-02, -

In [ ]:
#3. Concept
# Indexing and slicing
#1. Indexing : It is the process of fetching a single element from an array
# Syntax:
# 1D -->  arr[index]
# 2D -->  arr[row_index, col_index]
# 3D -->  arr[row_index, col_index, val_index]

# 1D
arr1 = np.arange(1,11)
arr1[5]
arr1[3]
arr1[-1]
# print(arr1[5])

# 2D
arr2 = np.array(([1,2,3],
                 [4,5,6],
                 [6,7,8]))
arr2[1,1]
arr2[2,1]
arr2[0,2]
arr2[2,0]

#3D

arr3 = np.array([[[1,2,3,4],
                  [6,7,8,9]],

                 [[4,4,6,7],
                  [7,8,9,0]]])
arr3[1,0,2]
arr3[0,1,2]
arr3[1,1,2]


np.int64(9)

In [ ]:
# Slicing on arrays: It is the process of fetching multiple values from a given array.
# Syntax:
# 1D ---> arr[si:ei+=1:upd/step]
# 2D ---> arr[row_slice, col_slice]
# 3D ---> arr[row_slice, col_slice, val_slice]

# 1D slicing:

arr = np.arange(1,7)
arr[:3]
arr[1:5]
arr[::-1]      # Which will give reverse order
arr[0::2]      # where even index is there i want that values.
arr[1::2]      # odd index position.

# 2D slicing:

arr = np.array([[1,2,3,4],
                [3,4,5,6],
                [6,7,7,8]])
arr[0:1,:]
arr[0:2,0:2]
arr[0:2,2:]
arr[2:,:]     # "::"--> means it will fetch all the records from the row
arr[::2,:2]
arr[:,1::2]



# 3D Slicing

arr = np.array([[[1,2,3,4],
                 [6,7,8,9]],
                [[3,4,5,6],
                 [6,9,8,0]]])
arr[0:1,1:,:]
arr[0:1,:,0:3]
arr[:,:,0:2]

array([[[1, 2],
        [6, 7]],

       [[3, 4],
        [6, 9]]])

In [ ]:
#4. Operations on Arrays
# We have to perform in 3 types

#1. Array with array
#2. Array with constants/scalar
#3. Math operations using inbuilt methods


#1. Array with array: Another name of array with array operation is called "Vectorization".

# Element wise operations are performed.
# arr1 operator arr2 (two array operands)

# Rules:-
# 1. We need minimum of two arrays.
# 2. Both arrays should be of same length

# Operators: +,-,*,/,//,%
# Floor division will give only the integers.

arr1 = np.arange(0,6)
arr2 = np.arange(4,10)
print(arr1)
print(arr2)
arr1+arr2
arr1-arr2
arr1*arr2     # It say element wise operations
arr1/arr2
arr1//arr2
arr1%arr2
arr1 & arr2
arr1 | arr2
arr1 ^ arr2
~arr1

arr1.all() and arr2.all()    # If non-default all the values are non- default value then it will return true.If we have one false the final output will be false.
arr1.any() and arr2.any()    # True
not arr1.all()  #True
arr1.all() #False


[0 1 2 3 4 5]
[4 5 6 7 8 9]


np.False_

In [ ]:
# 2D Array

arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[1,2,3]])
arr1+arr2

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
#arr2 = np.array([[1,2,3,4]])
#For the above one we get this ValueError: operands could not be broadcast together with shapes (2,3) (4,)
#Numpy always check dimensions from right to left.
arr2 = np.array([[1,2,3]])
arr1+arr2
arr1-arr2
arr1*arr2
arr1/arr2
arr1//arr2
arr1%arr2
arr1 & arr2
arr1 | arr2
arr1 ^ arr2
~arr1


array([[-2, -3, -4],
       [-5, -6, -7]])

In [ ]:
#2. Array with constant/Scalar

#Syntax: arr operator constant/scalar

arr = np.arange(1,6)
print(arr)
arr + 2
2 + arr # It can be operator or constand / constant over array anything can work.
arr - 3
arr * 2.5
arr / 5
arr // 5
arr % 2
arr ** 2
arr & 2
arr << 1
arr >>1
arr | 2

[1 2 3 4 5]


array([3, 2, 3, 6, 7])

In [ ]:
#3. Math operations using inbuilt methods

arr = np.arange(1,11)
print(arr)

np.sum(arr)
np.mean(arr)
arr.size
np.min(arr)
np.max(arr)
np.sqrt(arr)
np.log(arr)
np.exp(arr)
np.cos(arr)
np.sin(arr)
np.add(arr,arr)
np.subtract(arr,arr)
np.median(arr)
np.multiply(arr,arr)
np.divide(arr,arr)

[ 1  2  3  4  5  6  7  8  9 10]


np.float64(5.5)

In [ ]:
#4. Broadcasting:- Eventhough the shapes are different vectorization will happen the process is called as broadcasting.

#Rule: Numpy always checks the shape from Right side --->Left.
#1. Same no.of columns should be there (or)
#2. Columns should be 1.
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[1],
                 [2]])
print("arr1: ",arr1.shape)
print("arr2: ",arr2.shape)

arr1 + arr2

arr1:  (2, 3)
arr2:  (2, 1)


array([[2, 3, 4],
       [6, 7, 8]])

# TASK


In [ ]:
# Creating and Reshaping Arrays
#1. Create Arrays:
# Create two Numpy arrays:
# A 1D array of 10 equally spaced values between 0 and 50.
np.linspace(0, 50, 10)


array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [ ]:
# A 2D array of shape (3*3) containing random integers between 5 and 20.
import numpy as np

arr = np.random.randint(5,20,(9))
arr.reshape(3,3)

array([[17, 13, 12],
       [ 9, 10,  7],
       [ 6, 15, 10]])

In [ ]:
# Array Dimensions:
#1. Print the dimensions of both the arrays.
arr2 = np.array(([1,2,3],
                 [4,5,6],
                 [6,7,8]))
arr.ndim
arr1.ndim
arr2.ndim

#2. Print the shape of both arrays
arr1.shape
arr2.shape

(3, 3)

In [ ]:
# Part-2: Indexing and slicing
# Indexing
# For the 2D array created in Part1, prin the element present at the 2nd row and 3rd row.
# Extract the first two rows and the last two columns of the array.

arr2[1,2]
arr2[0:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
# Part-3: Array Operations
#6. Array Arithmetic

#Create another 1D array of 10 integers between 1 and 10
arr1 = np.arange(1,11)
print(arr1)

#Perform the following element-wise operations between the 1D arrays created in Part1 and Part 3:
# Addition
# Multiplication
# Subtract a constant value from the array.
np.add(arr,arr)
np.multiply(arr,arr)
np.subtract(arr,arr)

[ 1  2  3  4  5  6  7  8  9 10]


array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Random Number
# Create a 1D array of 5 random values between 0 and 1.
np.random.rand(5)

#Create another 1D array of 5 random values between -1 and 1.
np.random.randint(-1,1,5)

array([ 0, -1,  0,  0, -1])

In [ ]:
#Part-5: Bonus
#8. Challenge Task:
# Write a program that asks the user to input a number(n), and then generates an n*n array of random integers between 1 and 100.
import numpy as np

n = int(input("Enter num:" ))
arr=np.random.randint(1,101,(n,n))
print(arr)
print(arr.shape)


Enter num:3
[[99 71  3]
 [58 93 21]
 [56 53 88]]
(3, 3)


In [ ]:
# Find the sum of all the elements in the array and print the result.

arr = list(map(int, input("Enter the elements: ").split()))
total = sum(arr)
print("Sum of array elements =", total)


Enter the elements: 2
Sum of array elements = 2
